//! pass-mgr-ffi — the UniFFI boundary that lets the Compose Multiplatform mobile
//! app drive the audited [`pass_mgr_core`] vault without reimplementing any
//! crypto, storage, or recovery logic.
//!
//! # What this crate is
//!
//! A *thin, additive* wrapper. The security-critical core (two-password Argon2id
//! KDF, XChaCha20-Poly1305, the partitioned crash-safe volume/manifest format,
//! and the corruption-fails-closed recovery) lives in `pass-mgr-core` and is
//! reused **verbatim**. This crate only:
//!   * holds an opaque, mutex-guarded [`OpenVault`] behind a UniFFI interface,
//!   * exposes flat value DTOs (Kotlin/Swift data classes) for the five record
//!     types, and
//!   * maps the rich [`CoreVaultError`] down to a small, stable, **no-leak**
//!     [`VaultError`] (wrong-password and corrupt both collapse to one variant,
//!     exactly like the desktop's generic "can't open" message).
//!
//! # v1 scope — READ-ONLY
//!
//! Open with the two passwords, browse the five tabs, view a record, read its
//! edit history. No create/edit/delete/documents/rekey yet (those are additive
//! follow-ups). A read-only open writes nothing to disk and never takes the
//! single-writer lock.
//!
//! # Security downgrade (disclosed)
//!
//! Returning a record DTO copies its fields — including a cleartext password —
//! into the JVM/Swift heap, where `ZeroizeOnDrop` cannot reach and the GC/ARC
//! may duplicate the bytes. This is an inherent, documented downgrade versus the
//! desktop. The host must minimise copies, fetch history explicitly (it can
//! contain old/new passwords), and clear clipboard/fields itself.

// NOTE: this crate intentionally does NOT `#![forbid(unsafe_code)]` — the UniFFI
// scaffolding generated by `setup_scaffolding!()` contains `unsafe`. The core,
// which holds all the real logic, keeps its crate-wide `forbid`.

use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use pass_mgr_core::records::{self, Record};
use pass_mgr_core::vault::{OpenVault, VaultError as CoreVaultError};

uniffi::setup_scaffolding!();

// ---------------------------------------------------------------------------
// Error: a small, stable, no-leak surface mapped from CoreVaultError.
// ---------------------------------------------------------------------------

/// Stable error surface for the mobile host. Crucially, a wrong password and a
/// corrupt/tampered vault collapse to the SAME [`VaultError::WrongPasswordOrCorrupt`]
/// variant with no detail, so the FFI never becomes a correct-password oracle —
/// mirroring the desktop's single generic failure message.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum VaultError {
    /// The two passwords were wrong, OR the vault file is corrupt/tampered. These
    /// are deliberately indistinguishable (no leak). Re-check both passwords and
    /// their order first.
    #[error("wrong passwords, or the vault is corrupt")]
    WrongPasswordOrCorrupt,
    /// No vault file exists at the given location.
    #[error("no vault found at the given location")]
    NotFound,
    /// An interrupted password change is pending; it must be finished on a
    /// writable (desktop) open before the vault can be read here.
    #[error("an interrupted password change is pending; finish it on desktop (--write)")]
    RekeyPending,
    /// A document referenced by the vault is missing from the store — possible
    /// tampering or a rollback to an older snapshot.
    #[error("a referenced document is missing (possible tampering or rollback)")]
    ArchiveMismatch,
    /// Another writable session holds the vault (should not occur for read-only).
    #[error("the vault is open in another session")]
    Locked,
    /// No record with the requested id exists in that tab.
    #[error("record not found")]
    RecordNotFound,
    /// A low-level I/O error touching the vault directory.
    #[error("I/O error")]
    Io,
    /// An unexpected internal error.
    #[error("internal error")]
    Internal,
}

impl From<CoreVaultError> for VaultError {
    fn from(e: CoreVaultError) -> Self {
        match e {
            CoreVaultError::NotFound(_) => VaultError::NotFound,
            CoreVaultError::RekeyPending => VaultError::RekeyPending,
            CoreVaultError::ArchiveMismatch => VaultError::ArchiveMismatch,
            CoreVaultError::Locked => VaultError::Locked,
            CoreVaultError::Io(_) => VaultError::Io,
            // Everything that could discriminate a wrong password from a damaged
            // vault — the AEAD decrypt failure, bad magic/version/params, a
            // truncated file, a JSON/storage decode failure — collapses to ONE
            // generic variant so there is no correct-password oracle.
            CoreVaultError::Crypto(_)
            | CoreVaultError::BadMagic
            | CoreVaultError::BadVersion(_)
            | CoreVaultError::Truncated
            | CoreVaultError::BadParams
            | CoreVaultError::Json(_)
            | CoreVaultError::Storage(_) => VaultError::WrongPasswordOrCorrupt,
            // Not reachable on a read-only open, but map defensively.
            CoreVaultError::AlreadyExists(_)
            | CoreVaultError::ReadOnly
            | CoreVaultError::TooLarge
            | CoreVaultError::NoSuchPartition(_) => VaultError::Internal,
        }
    }
}

// ---------------------------------------------------------------------------
// Value DTOs — flat mirrors of the five records.rs structs (read views).
// History is NOT bundled (it can embed old/new passwords); fetch it explicitly.
// ---------------------------------------------------------------------------

/// Which of the five tabs / record collections to operate on.
#[derive(Debug, Clone, Copy, uniffi::Enum)]
pub enum RecordKind {
    Instruction,
    TrustWill,
    AssetLiability,
    Account,
    RealEstate,
}

/// One row in a tab's master list.
#[derive(uniffi::Record)]
pub struct RecordSummary {
    pub id: String,
    /// Human label (same logic the desktop list uses).
    pub label: String,
}

/// One timestamped history / audit entry. `detail` MAY contain cleartext old/new
/// field values (including passwords) by design — gate/redact on the host.
#[derive(uniffi::Record)]
pub struct Change {
    pub at: i64,
    pub action: String,
    pub detail: String,
}

#[derive(uniffi::Record)]
pub struct Instruction {
    pub id: String,
    pub title: String,
    pub description: String,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(uniffi::Record)]
pub struct TrustWill {
    pub id: String,
    pub document: String,
    pub usage: String,
    /// Volume file id of an attached document, if any (opening it is post-MVP).
    pub file: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(uniffi::Record)]
pub struct AssetLiability {
    pub id: String,
    pub kind: String,
    pub description: String,
    pub owner: String,
    pub approx_value: String,
    pub as_of_date: String,
    pub institution: String,
    pub asset_type: String,
    pub url: String,
    pub beneficiary: String,
    pub review: bool,
    pub statement: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(uniffi::Record)]
pub struct Account {
    pub id: String,
    pub account_type: String,
    pub account_subtype: String,
    pub owner: String,
    pub username: String,
    /// Cleartext. Crosses into the JVM/Swift heap — see the crate-level note.
    pub password: String,
    pub description: String,
    pub url: String,
    pub review: bool,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(uniffi::Record)]
pub struct RealEstate {
    pub id: String,
    pub address: String,
    pub ownership: String,
    pub taxes: String,
    pub hoa: String,
    pub income_account: String,
    pub financing_account: String,
    pub payment_account: String,
    pub created_at: i64,
    pub updated_at: i64,
}

// --- core -> DTO mappers ---------------------------------------------------

fn map_change(c: &records::Change) -> Change {
    Change { at: c.at, action: c.action.clone(), detail: c.detail.clone() }
}

fn map_instruction(r: &records::Instruction) -> Instruction {
    Instruction {
        id: r.id.clone(),
        title: r.title.clone(),
        description: r.description.clone(),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_trust_will(r: &records::TrustWill) -> TrustWill {
    TrustWill {
        id: r.id.clone(),
        document: r.document.clone(),
        usage: r.usage.clone(),
        file: r.file.clone(),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_asset(r: &records::AssetLiability) -> AssetLiability {
    AssetLiability {
        id: r.id.clone(),
        kind: r.kind.clone(),
        description: r.description.clone(),
        owner: r.owner.clone(),
        approx_value: r.approx_value.clone(),
        as_of_date: r.as_of_date.clone(),
        institution: r.institution.clone(),
        asset_type: r.asset_type.clone(),
        url: r.url.clone(),
        beneficiary: r.beneficiary.clone(),
        review: r.review,
        statement: r.statement.clone(),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_account(r: &records::Account) -> Account {
    Account {
        id: r.id.clone(),
        account_type: r.account_type.clone(),
        account_subtype: r.account_subtype.clone(),
        owner: r.owner.clone(),
        username: r.username.clone(),
        password: r.password.clone(),
        description: r.description.clone(),
        url: r.url.clone(),
        review: r.review,
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

fn map_real_estate(r: &records::RealEstate) -> RealEstate {
    RealEstate {
        id: r.id.clone(),
        address: r.address.clone(),
        ownership: r.ownership.clone(),
        taxes: r.taxes.clone(),
        hoa: r.hoa.clone(),
        income_account: r.income_account.clone(),
        financing_account: r.financing_account.clone(),
        payment_account: r.payment_account.clone(),
        created_at: r.created_at,
        updated_at: r.updated_at,
    }
}

// ---------------------------------------------------------------------------
// The opaque unlocked-vault handle.
// ---------------------------------------------------------------------------

/// An unlocked vault. Opaque to the host: the derived key never crosses the FFI.
/// Wraps the core [`OpenVault`] behind a mutex so the host can hold exactly one
/// handle and every call is serialised (this stands in for the desktop's
/// cross-process single-writer file lock, which a single app process doesn't
/// need). Dropping the handle runs the core's zeroize-on-drop.
#[derive(uniffi::Object)]
pub struct Vault {
    inner: Mutex<OpenVault>,
}

/// Open an existing vault **read-only** with the two passwords, in order.
///
/// `dir` is the app-private directory that holds `vault.pmv` (+ `manifest/`,
/// `volume/`) — the host hands in its sandbox path; arbitrary user paths are not
/// accepted. `pw1`/`pw2` are the raw password bytes; the host should overwrite
/// its copies afterwards (Rust only borrows them and never stores them).
#[uniffi::export]
pub fn open_vault(dir: String, pw1: Vec<u8>, pw2: Vec<u8>) -> Result<Arc<Vault>, VaultError> {
    let path = PathBuf::from(dir).join("vault.pmv");
    let ov = OpenVault::open_read_only(path, &pw1, &pw2)?;
    Ok(Arc::new(Vault { inner: Mutex::new(ov) }))
}

#[uniffi::export]
impl Vault {
    /// Human-readable notice if the live `vault.pmv` was unreadable and the vault
    /// was recovered from an in-place redundant copy (a roll-forward/rollback);
    /// `None` on a normal open. Surface it so the user is rollback-aware.
    pub fn recovery_notice(&self) -> Option<String> {
        self.lock().recovery_notice().map(|s| s.to_string())
    }

    /// The monotonic write counter of the snapshot just opened. A surprise drop
    /// versus a remembered value signals a whole-file rollback to an older copy.
    pub fn generation(&self) -> u64 {
        self.lock().opened_generation()
    }

    /// Unix-seconds timestamp the vault was previously opened (0 if never).
    pub fn previous_access(&self) -> i64 {
        self.lock().previous_access()
    }

    /// The master list for one tab: `{id, label}` per record, in stored order.
    pub fn list_records(&self, kind: RecordKind) -> Vec<RecordSummary> {
        let ov = self.lock();
        let v = &ov.vault;
        match kind {
            RecordKind::Instruction => v.instructions.iter().map(summary).collect(),
            RecordKind::TrustWill => v.trust_wills.iter().map(summary).collect(),
            RecordKind::AssetLiability => v.assets.iter().map(summary).collect(),
            RecordKind::Account => v.accounts.iter().map(summary).collect(),
            RecordKind::RealEstate => v.real_estate.iter().map(summary).collect(),
        }
    }

    /// How many records are in a tab (cheap, no cleartext crosses the boundary).
    pub fn count(&self, kind: RecordKind) -> u32 {
        let ov = self.lock();
        let v = &ov.vault;
        let n = match kind {
            RecordKind::Instruction => v.instructions.len(),
            RecordKind::TrustWill => v.trust_wills.len(),
            RecordKind::AssetLiability => v.assets.len(),
            RecordKind::Account => v.accounts.len(),
            RecordKind::RealEstate => v.real_estate.len(),
        };
        n as u32
    }

    pub fn get_instruction(&self, id: String) -> Result<Instruction, VaultError> {
        let ov = self.lock();
        ov.vault
            .instructions
            .iter()
            .find(|r| r.id == id)
            .map(map_instruction)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_trust_will(&self, id: String) -> Result<TrustWill, VaultError> {
        let ov = self.lock();
        ov.vault
            .trust_wills
            .iter()
            .find(|r| r.id == id)
            .map(map_trust_will)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_asset(&self, id: String) -> Result<AssetLiability, VaultError> {
        let ov = self.lock();
        ov.vault
            .assets
            .iter()
            .find(|r| r.id == id)
            .map(map_asset)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_account(&self, id: String) -> Result<Account, VaultError> {
        let ov = self.lock();
        ov.vault
            .accounts
            .iter()
            .find(|r| r.id == id)
            .map(map_account)
            .ok_or(VaultError::RecordNotFound)
    }

    pub fn get_real_estate(&self, id: String) -> Result<RealEstate, VaultError> {
        let ov = self.lock();
        ov.vault
            .real_estate
            .iter()
            .find(|r| r.id == id)
            .map(map_real_estate)
            .ok_or(VaultError::RecordNotFound)
    }

    /// A record's edit history, newest concerns last. Fetched explicitly (never
    /// bundled into the record DTO) because `detail` can contain cleartext
    /// old/new passwords — the host can gate or redact it.
    pub fn get_history(&self, kind: RecordKind, id: String) -> Result<Vec<Change>, VaultError> {
        let ov = self.lock();
        let v = &ov.vault;
        let history = match kind {
            RecordKind::Instruction => v.instructions.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::TrustWill => v.trust_wills.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::AssetLiability => v.assets.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::Account => v.accounts.iter().find(|r| r.id == id).map(|r| &r.history),
            RecordKind::RealEstate => v.real_estate.iter().find(|r| r.id == id).map(|r| &r.history),
        };
        history
            .map(|h| h.iter().map(map_change).collect())
            .ok_or(VaultError::RecordNotFound)
    }

    /// The vault-wide audit log (created/deleted/opened/compacted events).
    pub fn audit_log(&self) -> Vec<Change> {
        self.lock().vault.audit.iter().map(map_change).collect()
    }
}

impl Vault {
    /// Lock the inner handle, recovering from a poisoned mutex (a panic in a
    /// previous call) by taking the guard anyway — the core data is still valid
    /// and there is only one handle, so there is nothing to corrupt.
    fn lock(&self) -> std::sync::MutexGuard<'_, OpenVault> {
        self.inner.lock().unwrap_or_else(|p| p.into_inner())
    }
}

fn summary<R: Record>(r: &R) -> RecordSummary {
    RecordSummary { id: r.id().to_string(), label: r.label() }
}

// ---------------------------------------------------------------------------
// Host-side tests: drive the FFI surface against a real vault built with the
// core (no Android/iOS toolchain needed). Verifies open/list/get/history + the
// no-leak error mapping.
// ---------------------------------------------------------------------------
#[cfg(test)]
mod tests {
    use super::*;
    use pass_mgr_core::crypto::KdfParams;

    /// Build a small vault on disk with the core API, then return its directory.
    fn make_vault(dir: &std::path::Path, pw1: &[u8], pw2: &[u8]) {
        let path = dir.join("vault.pmv");
        // Cheap KDF params so the test is fast.
        let params = KdfParams { m_cost: 8, t_cost: 1, p_cost: 1 };
        let mut ov = OpenVault::create(path, pw1, pw2, params).unwrap();
        let mut acc = records::Account::new().unwrap();
        acc.account_type = "Financial".into();
        acc.username = "alice".into();
        acc.password = "s3cret".into();
        records::upsert(&mut ov.vault.accounts, acc);
        let mut ins = records::Instruction::new().unwrap();
        ins.title = "Funeral wishes".into();
        records::upsert(&mut ov.vault.instructions, ins);
        ov.save().unwrap();
    }

    fn tmp() -> std::path::PathBuf {
        let d = std::env::temp_dir().join(format!(
            "pmffi-{}-{}",
            std::process::id(),
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()
        ));
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    #[test]
    fn open_browse_and_view() {
        let dir = tmp();
        make_vault(&dir, b"one", b"two");

        let v = open_vault(dir.to_str().unwrap().to_string(), b"one".to_vec(), b"two".to_vec())
            .expect("opens with correct passwords");

        assert_eq!(v.count(RecordKind::Account), 1);
        assert_eq!(v.count(RecordKind::Instruction), 1);
        assert_eq!(v.count(RecordKind::RealEstate), 0);

        let accounts = v.list_records(RecordKind::Account);
        assert_eq!(accounts.len(), 1);
        assert_eq!(accounts[0].label, "Financial: alice");

        let acc = v.get_account(accounts[0].id.clone()).unwrap();
        assert_eq!(acc.username, "alice");
        assert_eq!(acc.password, "s3cret");

        // history exists (a "created" entry) and is fetched separately.
        let hist = v.get_history(RecordKind::Account, accounts[0].id.clone()).unwrap();
        assert!(!hist.is_empty());

        assert!(v.get_account("nope".into()).is_err());
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn wrong_password_and_corrupt_are_indistinguishable() {
        let dir = tmp();
        make_vault(&dir, b"one", b"two");

        // Wrong password -> generic error.
        let e = open_vault(dir.to_str().unwrap().to_string(), b"bad".to_vec(), b"two".to_vec())
            .err()
            .expect("open should fail");
        assert!(matches!(e, VaultError::WrongPasswordOrCorrupt));

        // Right passwords still open.
        assert!(
            open_vault(dir.to_str().unwrap().to_string(), b"one".to_vec(), b"two".to_vec()).is_ok()
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn missing_vault_reports_not_found() {
        let dir = tmp();
        let e = open_vault(dir.to_str().unwrap().to_string(), b"one".to_vec(), b"two".to_vec())
            .err()
            .expect("open should fail");
        assert!(matches!(e, VaultError::NotFound));
        std::fs::remove_dir_all(&dir).ok();
    }
}
